site_name: Candella Documentation
site_author: Project Alice and Unscripted Team
site_description: 'Documentation site for Candella framework'
docs_dir: mkdocs/

edit_uri: ""

# Material Theme configuration
theme:
    favicon: images/favicon.ico
    name: material
    logo: 'images/logo.svg'
    palette:
        primary: 'grey'
        accent: 'yellow'
    font:
        text: 'Inter'
        code: 'Fira Code'
    feature:
      tabs: true

extra_css:
  - 'https://rsms.me/inter/inter.css'
  - 'https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.207/distr/fira_code.css'

# Repository
repo_name: 'ProjectAliceDev/AliceOS'
repo_url: 'https://github.com/ProjectAliceDev/aliceos'

copyright: 'Copyright &copy; 2018 - 2019 Project Alice.'

extra:
    social:
    - type: 'github'
      link: 'https://github.com/projectalicedev'
    - type: 'twitter'
      link: 'https://twitter.com/justaliceproj'

markdown_extensions:
- admonition
- codehilite:
    guess_lang: true
- toc:
    permalink: true
