name: Run Project Tests
on: [push, pull_request]

jobs:
  lint:
    name: Lint Project with SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        renpy-versions:
          - '7.4.2'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50    
      - name: Fetch dependencies
        run: |
          pip install pipenv
          pipenv sync
      - name: Run tests
        run: pytest ./tests/
