name: Update Project Version
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lint:
    name: Update Version Strings
    runs-on: ubuntu-latest

    steps:
      - name: Clone source
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Update version strings
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run update_release # Run custom `test` command defined in the `[scripts]` block of Pipfile
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: ":wrench: Update version strings"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
          add: "game/System/release_info.json"
          signoff: true

